# Generated by Django 5.1.15 on 2026-04-16 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150)),
                ('national_id_number', models.CharField(blank=True, max_length=80)),
                ('preferred_mobile_money_operator', models.CharField(blank=True, choices=[('mtn', 'MTN MoMo'), ('orange', 'Orange Money')], max_length=10)),
                ('preferred_mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('textile', 'Textile'), ('ewaste', 'E-Waste')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mobile_money_operator', models.CharField(choices=[('mtn', 'MTN MoMo'), ('orange', 'Orange Money')], max_length=10)),
                ('mobile_money_number', models.CharField(max_length=20)),
                ('mobile_money_reference', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('lot_qr_code', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_supplier_transactions', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='suppliers.supplierprofile')),
            ],
        ),
    ]
