# Generated by Django 5.1.15 on 2026-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertransaction',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='suppliers/qr_codes/'),
        ),
    ]
