# Generated by Django 5.1.15 on 2026-04-16 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collection_points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('report', 'Citizen report'), ('drop_point', 'Free drop-off point'), ('scheduled', 'Scheduled round')], max_length=20)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('en_route', 'En route'), ('on_site', 'On site'), ('collected', 'Collected'), ('delivered', 'Delivered to center'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_photo', models.ImageField(blank=True, upload_to='confirmations/')),
                ('collected_weight_kg', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('lot_qr_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('collection_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collection_points.collectionpoint')),
                ('collector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
