# Generated by Django 5.1.15 on 2026-04-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('reports', '0001_initial'),
        ('sorting_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='destination_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sorting_center.sortingcenter'),
        ),
        migrations.AddField(
            model_name='mission',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.wastereport'),
        ),
    ]
