# Generated by Django 5.1.15 on 2026-04-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use first day of month.', unique=True)),
                ('total_waste_collected_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_waste_recycled_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('co2_avoided_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active_citizens', models.PositiveIntegerField(default=0)),
                ('active_collectors', models.PositiveIntegerField(default=0)),
                ('active_suppliers', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use first day of month.', unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier_payouts', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('operational_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
