# Generated by Django 5.1.15 on 2026-04-16 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('point_type', models.CharField(choices=[('paid', 'Paid Collection Point'), ('free', 'Free Drop-Off Point')], max_length=20)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('district', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('accepts_plastic', models.BooleanField(default=True)),
                ('accepts_metal', models.BooleanField(default=True)),
                ('capacity_kg_day', models.FloatField(default=500)),
                ('current_stock_kg', models.FloatField(default=0)),
                ('fill_level', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('plastic_price_kg', models.FloatField(blank=True, help_text='Purchase price FCFA/kg', null=True)),
                ('metal_price_kg', models.FloatField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('opening_days', models.CharField(blank=True, help_text='e.g. Mon-Fri, Sat', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('full', 'Full — max capacity reached')], default='active', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='collection_points/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
