# Generated by Django 5.1.15 on 2026-04-16 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('metal', 'Metal'), ('mixed', 'Mixed')], max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='reports/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('text_address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('estimated_quantity_kg', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'Collection in progress'), ('collected', 'Collected'), ('processed', 'Processed at sorting center'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
